version: 0.0
os: linux
files:
  - source: /build/
    destination: /home/ec2-user/my-nodejs-app

hooks:
  AfterInstall:
    - location: scripts/install.sh
    - timeout: 180
    - runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
    - timeout: 180
    - runas: ec2-user
